### ISSUE TITLE
Parsing error when quotation marks exist in json value

### ISSUE THREAD

**Issue by varHarrie** [PatrickChen928/json2ts#9]
<table>
<tr>
 <td>Example</td>
 <td>Result</td>
<tr>
 <td>{
  "foo": "''"
}</td>
<td>value is illegal</td>
<tr>
 <td>{
  "foo": "'', ''"
}</td>
<td>type Result$0Type = {
  foo: string
  , : string
}
</td>
</table>

**Comment by varHarrie** [comment]
![image](https://github.com/PatrickChen928/json2ts/assets/14304201/1a15db12-3c21-4a4e-ae89-0fa6ee809d50)
@PatrickChen928 There are still some problems with the latest version. In addition, [0.2.6 does not seem to be released to npm](https://www.npmjs.com/package/@cyly/json2ts?activeTab=versions).

**Comment by PatrickChen928** [comment]
I think the cache causes this. You can force refresh the page and try again.

NPM package is not updated yet, but the page used static js file.

**Comment by varHarrie** [comment]
![image](https://github.com/PatrickChen928/json2ts/assets/14304201/f2962f4c-531f-46cb-91de-679f0dad559f)
It's not caused by the cache. There is also a problem with 0.2.6 on npm.
https://www.val.town/v/varharrie/json2ts_example

**Comment by PatrickChen928** [comment]
It should be fixed in v0.2.7, try again, thanks.

**Comment by PatrickChen928** [comment]
<img width="924" alt="image" src="https://github.com/PatrickChen928/json2ts/assets/25942328/90c479d9-d73f-43fb-a585-771e2a31c3f5">
